### ISSUE TITLE
Signalling molecule shifts

### ISSUE THREAD

**Issue by ACRichard** [MarioniLab/archive-cydar#1]
For signalling molecules that exhibit strong shifts in expression between conditions, cydar is very good at picking up differential abundance.  However, particularly in very high-dimensional data, if all other marker intensities are equal for a subpopulation and one condition only increases intensity of a signalling marker slightly, the shift will not be detected as a differentially abundant hypersphere.  In this situation, it may be beneficial to have the option to leave the signalling marker out of the initial hypersphere assigment phase of analysis and then compare median intensity of the signalling marker between conditions within a hypersphere. Of course, this will only work if the intensity of the whole subpopulation within the hypershere shifts, because if only a small fraction of the cells in the hypershere shift in signalling marker intensity, the median will not change and the shift will remain undetected.

**Comment by LTLA** [comment]
Note to self:
- An alternative is to test for any type of changes in the distribution, where you'd have to bin across the intensity range and test each bin for differential abundance. This would detect the big shifts in small subpopulations, as well as the small(er) shifts in big subpopulations, albeit probably without the same sensitivity as a median-based approach. This should provide a bridge between the two extremes; in fact, it could be done using the differential splicing machinery that's already in _edgeR_.
- Regardless, you wouldn't be able to figure out if the same cells had multiple signalling molecules being turned on if you were analysing each signalling molecule separately.

Be careful with going overboard with the first point, though. Hypersphere counts are already small, so if you try to bin at too high resolution, or in multiple dimensions, then you'll probably end up with very low counts. In fact, that's the inherent trade-off with using smaller radii at fewer dimensions; you get higher resolution for those dimensions, but the count sizes will inevitably be smaller when you re-count in extra dimensions. Performing the original counting in all dimensions sacrifices resolution to preserve count size right off the bat.

**Comment by LTLA** [comment]
Done. The `medIntensities` function identifies shifts in the median within each hypersphere, while the `recountCells` function performs quick recounting of cells with new markers of interest.
